# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform=neoforge

# Mod properties
mod_version=1.0.0
maven_group=net.aros
archives_name=aros-player-plushies

# Minecraft properties
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.3

# Dependencies
neoforge_version = 21.1.31
yarn_mappings_patch_version = 1.21+build.4